"""change file storage to URL

Revision ID: 2cf42457745e
Revises: 85395fa29bdc
Create Date: 2025-08-08 12:07:30.677732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cf42457745e'
down_revision = '85395fa29bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggestion_file_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('suggestion_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggestion_file', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('suggestion_file_url')

    # ### end Alembic commands ###
