"""modve

Revision ID: 38c53a7659a4
Revises: 
Create Date: 2025-08-07 20:28:01.804879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38c53a7659a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # إنشاء ENUM قبل استخدامه
    suggestion_status_enum = postgresql.ENUM('reviewed', 'unreviewed', name='suggestionstatus')
    suggestion_status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complaint_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('suggestion_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'complaints', ['complaint_id'], ['complaint_id'])
        batch_op.create_foreign_key(None, 'suggestions', ['suggestion_id'], ['suggestion_id'])

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggestion_file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('suggestion_status', suggestion_status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    suggestion_status_enum = postgresql.ENUM('reviewed', 'unreviewed', name='suggestionstatus')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_column('suggestion_status')
        batch_op.drop_column('suggestion_file_name')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('suggestion_id')
        batch_op.drop_column('complaint_id')

    # حذف الـ ENUM بعد إلغاء العمود
    suggestion_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###