"""rename suggestion file fields to complaint

Revision ID: 5a9923ede271
Revises: 2cf42457745e
Create Date: 2025-08-08 13:06:21.330934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a9923ede271'
down_revision = '2cf42457745e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complaint_file_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('complaint_file_name', sa.String(length=255), nullable=True))
        batch_op.drop_column('complaint_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complaint_file', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('complaint_file_name')
        batch_op.drop_column('complaint_file_url')

    # ### end Alembic commands ###
